name: .NET Core
on:
  push:
  pull_request:
  release:
    types:
      - published
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: EmbyClient.Dotnet
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/mmedic/index.json
  GITHUB_USER: mmedic
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Ensure GitHub NuGet Source
        run: |
          dotnet nuget add source $GITHUB_FEED \
            -n github \
            -u $GITHUB_USER \
            -p ${{ secrets.NUGET_REPO_PASSWORD }} \
            --store-password-in-clear-text

      - name: Restore
        run: dotnet restore SampleCode/RestApi/Net.RestSharp/$PROJECT_NAME/$PROJECT_NAME.*proj

      - name: Build
        run: dotnet build -c Release --no-restore SampleCode/RestApi/Net.RestSharp/$PROJECT_NAME/

      - name: Pack
        run: dotnet pack -v normal -c Release --no-restore --output nuget-packages --include-symbols --include-source SampleCode/RestApi/Net.RestSharp/$PROJECT_NAME/$PROJECT_NAME.*proj

      - name: Push to GitHub Feed
        run: |
          pwd
          ls -l ./nuget-packages
          dotnet nuget push ./nuget-packages/*.nupkg --api-key ${GITHUB_TOKEN} --source ${GITHUB_FEED} --skip-duplicate

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          dotnet nuget remove source github

          
  